# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    build: .
    image: api
    container_name: api
    env_file: 
      - path: ./.env
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: connectorPassword123*
      MYSQL_USER: ccs-videos-connector
      MYSQL_HOST : 127.0.0.1
      MYSQL_DATABASE: CCSVideos
    volumes:
      - /var/lib/mysql
      - ./_init_.sql:/docker-entrypoint-initdb.d/_init_.sql
    ports:
      - "3306:3306"

  